name: Build Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Zip
        run: bash bin/build-zip.sh

      - name: Create Release & Upload Assets
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.tag.outputs.tag }}
          tag: ${{ steps.tag.outputs.tag }}
          artifacts: wp-ajaxify.zip
