name: Build Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Tag
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Build Project
        run: git archive -o /tmp/wp-ajaxify.zip --prefix=wp-ajaxify/ ${{ steps.tag.outputs.tag }}

      - name: Create Release & Upload Assets
        id: create_release
        uses: ncipollo/release-action@v1.11.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.tag.outputs.tag }}
          tag: ${{ steps.tag.outputs.tag }}
          artifacts: /tmp/wp-ajaxify.zip
