name: Build release asset

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Build project
        run: git archive -o /tmp/wp-ajaxify-${{ steps.tag.outputs.tag }}.zip --prefix=wp-ajaxify/ ${{ steps.tag.outputs.tag }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/wp-ajaxify-${{ steps.tag.outputs.tag }}.zip
          asset_name: wp-ajaxify.zip
          asset_content_type: application/zip
